name: Configuration Issue

about: Report an issue related to project configuration

labels: configuration

---

**Describe the issue**
A clear and concise description of the configuration issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Steps to Reproduce**
If applicable, steps to reproduce the issue:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Additional context**
Add any other context about the issue here.
