name: Other Issue

about: For issues not covered by other templates

---

**Describe the issue**
A clear and concise description of the issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the issue here.
